apiVersion: v1
appVersion: "2.4.0"  # notice that this is not used anywhere, see vaules.yaml image.tag
description: >
  Store and serve massive amounts of time series data without losing
  granularity.
home: https://github.com/Gradiant/charts
sources:
  - http://opentsdb.net/
  - https://github.com/Gradiant/charts
  - https://github.com/Gradiant/dockerized-opentsdb
icon: http://opentsdb.net/img/logo_header.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: opentsdb
version: 0.1.3
keywords:
  - hadoop
  - hbase
  - hdfs
  - opentsdb
  - zookeeper
