annotations:
  category: bigdata
apiVersion: v2
appVersion: 6.0.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Helm for jupyter single server with pyspark support
engine: gotpl
home: "https://jupyter.org"
icon: https://jupyter.org/assets/main-logo.svg
keywords:
  - juypter
  - notebook
  - spark
maintainers:
  - email: cgiraldo@gradiant.org
    name: cgiraldo
name: jupyter
sources:
  - https://github.com/gradiant/charts
  - "https://github.com/astrobounce/helm-jupyter"
version: 0.1.8

