apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "spark.fullname" . }}-exporter
data:
  metrics.properties: |-
    *.sink.graphite.class=org.apache.spark.metrics.sink.GraphiteSink
    *.sink.graphite.host=localhost
    *.sink.graphite.port=9109
    *.sink.graphite.period=10
    *.sink.graphite.unit=seconds
    master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource


