apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: namenode
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  ports:
  - name: dfs
    port: {{ .Values.nameNode.port }}
    protocol: TCP
  - name: webhdfs
    port: 50070
  selector:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: namenode
    app.kubernetes.io/instance: {{ .Release.Name }}
