apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jupyter.name" . }}
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "jupyter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.externalPort | default 8888 }}
      targetPort: http
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort.http))) }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
      targetPort: 8888