apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}-master
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: master
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hbase.name" . }}
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hbase.fullname" . }}-master
  replicas: {{ .Values.hbase.master.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hbase.name" . }}
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: {{ include "hbase.name" . }}
                app.kubernetes.io/component: master
                {{- include "hbase.labels" . | nindent 16 }}
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "hbase.name" . }}
                  app.kubernetes.io/component: master
                  {{- include "hbase.labels" . | nindent 18 }}
        {{- end }}
      {{- if .Values.prometheus.enabled }}      
      initContainers:
      - name: inject-exporter-jar
        image: "{{ .Values.prometheus.image }}:{{ .Values.prometheus.imageTag }}"
        env:
        - name: SHARED_VOLUME_PATH
          value: /jmx-exporter
        volumeMounts:
        - mountPath: /jmx-exporter
          name: jmx-exporter
      {{- end }}    
      containers:
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/bash"
        - "/tmp/hbase-config/bootstrap.sh"
        - "-d"
        - "master"
        env:
        - name: HADOOP_USER_NAME
          value: {{ .Values.conf.hadoopUserName }}
        resources:
{{ toYaml .Values.hbase.master.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config
        {{- if .Values.prometheus.enabled }}      
        - name: jmx-exporter  
          mountPath: /jmx-exporter
        - name: exporter-config
          mountPath: /etc/exporter
        {{- end }}
      volumes:
      - name: hbase-config
        configMap:
          name: {{ include "hbase.fullname" . }}
      {{- if .Values.prometheus.enabled  }}
      - name: jmx-exporter
        emptyDir: {}      
      - name: exporter-config
        configMap:
          name: {{ include "hbase.fullname" . }}-exporter
      {{- end }}
