apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    {{- include "hive.labels" . | nindent 4 }}
data:
  startup.sh: |-
{{ tpl (.Files.Get "resources/startup.sh") . | indent 4 }}
  hive-site.xml: |
{{ tpl (.Files.Get "resources/config/hive-site.xml") . | indent 4 }}
